### ISSUE TITLE
Nodemon Issue

### ISSUE THREAD

**Issue by iMajorLeague32-1** [Dexvoo/IN-ServerStatus#1]
I'am recieving this error code, after running the npm run dev command. (I did run the npm install command prior)

[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/index.js`
[nodemon] Internal watch failed: EBUSY: resource busy or locked, lstat 'C:\pagefile.sys
![IN-ServerStatus Issue](https://user-images.githubusercontent.com/75959833/181141592-9667d6c6-5dda-4279-8041-842ae840cd6f.PNG)
'

**Comment by Dexvoo** [comment]
ive added a new command to start without nodemon (npm run start), really shouldn't use it as a dependency but its great for development, if you update and let me know if your issue persists c:

**Comment by iMajorLeague32-1** [comment]
Yes that did work, I did not however get the this "FiveMMessageID=".

**Comment by iMajorLeague32-1** [comment]
FiveMMessageID & Server Update (Sends Update to Discord) Does not seem to work unless i restart the BOT

**Comment by iMajorLeague32-1** [comment]
> FiveMMessageID & Server Update (Sends Update to Discord) Does not seem to work unless i restart the BOT



> Yes that did work, I did not however get the this "FiveMMessageID=".

Disregard, After Looking at it closely, the message id is the actual discord message id that is sent & i do see the last updated time changing every 60

**Comment by Dexvoo** [comment]
has this been resolved?
