### ISSUE TITLE
Getting Error Bot Going Down By Its Own

### ISSUE THREAD

**Issue by Supreme69X** [Dexvoo/IN-ServerStatus#2]
[The Bot Runs Work 2 Min fine When i start it But After some time it shows error and the bot Goes down And the "npm run commands" is Not working may be because off new update .]

[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node src/index.js`
Ready! Logged in as Horizon RolePlay Status#3928
Error: Error: read ECONNRESET
DError: Error: read ECONNRESET

![Screenshot 2022-07-27 233604](https://user-images.githubusercontent.com/76610632/181342378-009eef61-ea2b-4e34-ac54-58013bab8f0b.png)

**Comment by Dexvoo** [comment]
try running the bot with **npm run start**

**Comment by Supreme69X** [comment]
Not working with npm start too
![Screenshot 2022-07-28 182045](https://user-images.githubusercontent.com/76610632/181509311-e601659f-dac4-45f4-85e9-1cb496507e95.png)

**Comment by Dexvoo** [comment]
you need to update before you run the command

**Comment by Supreme69X** [comment]
Can u Elaborate what i need to update

**Comment by Dexvoo** [comment]
i pushed the command yesterday, you need to download it again to run the command
